# Generated by Django 2.1.3 on 2018-12-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20181205_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='linked_post',
            field=models.IntegerField(default=0),
        ),
    ]
