# Generated by Django 2.1.3 on 2018-12-05 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_post_lq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='lq',
            new_name='parent_post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='linked_post',
        ),
    ]
