# Generated by Django 2.1.3 on 2018-12-05 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20181205_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='parent_post',
            field=models.ForeignKey(default=-1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Post'),
        ),
    ]
