# Generated by Django 2.1.3 on 2018-12-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20181205_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='parent_post',
            new_name='group_post',
        ),
        migrations.AddField(
            model_name='post',
            name='depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='group_order',
            field=models.IntegerField(default=0),
        ),
    ]
