# Generated by Django 2.1.3 on 2018-12-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20181205_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='group_post',
            new_name='group_no',
        ),
    ]
