# Generated by Django 2.1.3 on 2018-12-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20181205_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group_order_2',
            field=models.IntegerField(default=0),
        ),
    ]
