# Generated by Django 2.1.3 on 2018-12-05 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_post_group_order_2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-group_no', 'group_order', 'group_order_2'), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
